# Site settings
title: Christy Zone
SEOTitle: 小黑的博客 | Christy Zone
header-img: img/home-background.jpg
email: bihanyuchristy@gmail.com
description: "Love life till death"
keyword: "Christy Zone, xiaoheifish, yuxiaohei, Java, Spring, Springboot"
url: "www.chrismo.top"     # your host, for absolute URL
baseurl: ""                # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
zhihu_username:     xiaohei-yu
github_username:    xiaoheifish
facebook_username:  Christy Yu



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# 评论系统

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 73a6b64acb9d4d6bfe33                            #生成的clientID
  clientSecret: 1f3def0c21dfab82d30d04d91e733e122a181a2a    #生成的clientSecret
  repo: xiaoheifish.github.io    #仓库名称
  owner: xiaoheifish    #github用户名
  admin: xiaoheifish
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: www.chrismo.top              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Love life till death"
sidebar-avatar: http://cdn.terabits-wx.cn/Christy-portrait.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: [
    {
        title: "Stack Overflow",
        href: "https://stackoverflow.com/"
    },{
        title: "V2EX",
        href: "https://www.v2ex.com/"
    },{
        title: "LeetCode",
        href: "https://leetcode.com/"
    }
]



